-- MySQL Script generated by MySQL Workbench
-- Wed Apr 17 22:02:33 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema time_tracking
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `time_tracking` ;

-- -----------------------------------------------------
-- Schema time_tracking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `time_tracking` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `time_tracking` ;

-- -----------------------------------------------------
-- Table `time_tracking`.`activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `time_tracking`.`activity` ;

CREATE TABLE IF NOT EXISTS `time_tracking`.`activity` (
  `activity_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`activity_id`),
  UNIQUE INDEX `activity_id_UNIQUE` (`activity_id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `time_tracking`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `time_tracking`.`user` ;

CREATE TABLE IF NOT EXISTS `time_tracking`.`user` (
  `user_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` INT(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `role` ENUM('ADMIN', 'USER') NOT NULL DEFAULT 'USER',
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `time_tracking`.`request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `time_tracking`.`request` ;

CREATE TABLE IF NOT EXISTS `time_tracking`.`request` (
  `request_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` ENUM('DELETE', 'ADD') NOT NULL,
  `activity` INT(10) UNSIGNED NOT NULL,
  `user` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`request_id`),
  UNIQUE INDEX `request_id_UNIQUE` (`request_id` ASC) VISIBLE,
  INDEX `fk_activity_req_id_idx` (`activity` ASC) VISIBLE,
  INDEX `fk_user_req_id_idx` (`user` ASC) VISIBLE,
  CONSTRAINT `fk_activity_req_id`
    FOREIGN KEY (`activity`)
    REFERENCES `time_tracking`.`activity` (`activity_id`),
  CONSTRAINT `fk_user_req_id`
    FOREIGN KEY (`user`)
    REFERENCES `time_tracking`.`user` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `time_tracking`.`track`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `time_tracking`.`track` ;

CREATE TABLE IF NOT EXISTS `time_tracking`.`track` (
  `track_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `activity` INT(10) UNSIGNED NOT NULL,
  `isActive` TINYINT(4) NOT NULL DEFAULT '0',
  `isComplete` TINYINT(4) NOT NULL DEFAULT '0',
  `elapsedTime` TIME NOT NULL DEFAULT '00:00:00',
  `user` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`track_id`),
  UNIQUE INDEX `idTrack_UNIQUE` (`track_id` ASC) VISIBLE,
  INDEX `fk_activity_id_idx` (`activity` ASC) VISIBLE,
  INDEX `fk_user_id_idx` (`user` ASC) VISIBLE,
  CONSTRAINT `fk_activity_id`
    FOREIGN KEY (`activity`)
    REFERENCES `time_tracking`.`activity` (`activity_id`),
  CONSTRAINT `fk_user_id`
    FOREIGN KEY (`user`)
    REFERENCES `time_tracking`.`user` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
